import SideBar from "@/Components/SideBar";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/Components/Navbar";

const fonts = localFont({
  src: [
    {
      path: "../../public/Fonts/PlusJakartaSans-Regular.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/Fonts/PlusJakartaSans-Medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/Fonts/PlusJakartaSans-SemiBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/Fonts/PlusJakartaSans-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--Font-primary",
});

export const metadata = {
  title: "Project Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <div className="flex justify-start items-start">
          <div className=" flex-1 flex-grow-[0.2]  ">
            <SideBar />
          </div>
          <div className="flex justify-start flex-col items-start min-h-screen flex-1 flex-grow-[0.6] ">
            <Navbar
              img={
                "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQA6AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQIDBQYHBAj/xABAEAABAwMCBAIIAwUGBwEAAAABAAIDBAUREiEGMUFRE2EHFCJCgZGhsXHB0RUjMuHwUmKCssLxM0NUZKLD4hf/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAQIDBAX/xAApEQADAAIBAwQBAwUAAAAAAAAAAQIDESEEEjEiMkFxMxOB8AUUI1Fh/9oADAMBAAIRAxEAPwDrY5IymgpUA7mlCQIQCoQkQCoQhACEiEAqUnAyeSTKqOK7nDbLLUyTPEYfG5rXlpcASOuCEBazzxQM1SyNY0dXHAXL+JvS/DRzsgslGZXsc9tQan2cEHGBgnz3XML7xReLvK4Vta6Q6PD1M9lrmg7HH5rxwWiWZnjVUrw0jmGquyyR16w+mS21B0XqB1O5z/ZfE0uaG+fXIW0oeLrFXzthpbjG97jhudgTjOMr51ip6SNo0yMfp5/10TmVVPS6ZKYtdgHLeo/rCjuJcn07UVUFO3M8rIx3ccKRu4zt81xi1ccRSWxlHd2OqQcNa7GXaDnAJ7jbddQ4VuVPcrNBJTT+IIx4bsjBBHQqyZVrRcFJhBShSQGEhSowgGppUmExwQDSmlPwmkICJ2yjcFK5MIQHmeN0ileEKQe8JQgJcKAATkg5pUA080qEqAQpMpUIACEhShAGwBJ5BfNPH/ElXeL5VsbUzinDi3QZnFhxyw3kF9Kv/hOOy+S7yHPvVdGHEn1qQAjqdZUMlDrZAZ3kRN1y7aR3K1lDwFdq0tkmmDM9c8l6OCOHHU07Kiow488Y6rrdBG1kYGMDyXPeTnSO2MSU7Zy9voprZXgmqZjqSFH/APl1e17g6QaR77eZ+C7QzGnZJJyCr3Mds/6Pne8WGssFZC2oOqMnLdgeXcLqHoirI3/tKne5rJ3ubLoHJzcYyPp81Jx/bBW2SdzWfvYP3jfgud8IXKpoeLra6Ak65Wxlvdruf0+y0x02ZZZSPohKEhGP0ShbnMCVCEAJClCQoBpTCpE0oCJwUTlMVG5AQlKhyEB7gnhManoACChJ0QChCaEuUAJUiEAiEqRAHMYPXZfLFdQvpOMKyllYWOjrJBpd21Ej6EL6nXAeOWuk9J9W4xiPcA7c8NG/xVbfBfGt0i8tt4pKCNjZXuc4DOlgzhaO18X2ioIj8cslB3a9qyUNnr6eJktAxup51Pkd7X0XsfYqqoh9Yqp2eI33o4C3b4nmuNHpPfg6O2rhMAlDvY7qmruMLRSyNgfI4ynk1rSSUljic7hxsEj8yYxqwqCo4duVJX+NSVIGonLnwawW+W4wfNTsr2ouJ7lTXSnmhjLg9zSNLxgnZcx4RjJ9IltjIJ01GC3scH8wulUtpqnMZPWvY6aM5D2gjbss1wVbxH6Upy6MvbE2RzXDYNJxjPzKvifJjnW5Ox9j5JUg3ShdRxCpUiUIARhKkQDSOyaQnpHICFyiepnqFyAhdzSodzQgPa1PCjanBAOSpAlQCYRhKkQAgoQUAiQpU0oBQVxv0pU8kHG0NQ8DRNE3S4dsY+7V2QLDelqzNq7I27Nk0Ptw1ObpzrYSOvTGPqq2tyaYq1R5uGqthga3V/CMFP4nvUVNTgFrywnBc3fCx9rrcUtZJFqLoaYTBo97uqGWquF5lbA92lp3BedLSFyJHo9/G0dIs/FVq/Zel0xEoO7cEu+QWhprqx0Ub3Bwhf8AwvcMfMLnFPwROyiZLHXUTZG5c/NQcHfGMY+KjlN4s1FJA1pqKbSXPcx4exgHflhS1oqns6hVTtdGdJBGN8Km4Hp2Ovdzq2t3fKG58mN/V5VZDcH0topjOf3r4S4tPQdFfejODNkfXOJ1VMz3AadgM/7K2Nboyy0lOjXoQlXUcIIQhAKhCEAhTXFOITSgI3KFymcoXICJyErgkQHqYpFAwqTKAenKPKcgFKVNSoAKMoQUAJOqEIBwC8t1oo7jbamilHsTRlh+K9QS79EB80QVdVw9fJqWqaWzUr3wSMcNiN/mOvxWht1bTPoGPgjYdAAMbhty5qL0uupbjxNPVW5weadjYJnDkXtJyB3xkDPw6LGUNxMOGuzg/wASwqU/B1xkqWtnTabiynhxAaWI5OMcx9lYXu7im4dkfIxjZahulsYGNPmsNS3qB+h+I2gYGMb7Db+vNVtfdJa6QNDnPLsaWjJwqdr+TWsi1wXPr1ZeLjHQwFz56lzYYhzwP9t8rvFqoY7ZbqaiiADIIwwY69yuZeiylo7LWNkuz2x3GubopmuHIdRnoT/JdZPZbwlrg5Mu98jcpUmEoCuZAlQgIAQlSIATHJSUxxQDHKIp7io3FARuQkcUICWMqUFQxqUckA9OCaE5AKhKChAJlCRKgFSFRT1VPTDNRM2PsHHn8Oazly41pqeoFNRwvklIBLnbADuo2XnG6NSfZbqcQGgZJO2Fj+MeMKaipPUrXUxz1lQdBfE7IhafeyOvb+SzdRdK+/RVEtcT4bZGsigBwNXcjqs3dKd9PVSOAJ0xh7f8LgT9PuqO+dHTHTaj9Rs8VLQZFVC8YIldt3ydlU1fDxdKTGC0/itlDGauOOtjEYEoBaB7zcbH5KxgoRPzZuufbTN6iWYCi4XqJCQZGhueo3W54a4UpqMiUjVJjGohWMFvML92bFX9I1rIweQ+yh02R2SinuNqbU3W2SFxZ6vI5+3YNK2dgu0Vwo2B8oNTF7EjTsSR73nlZeruEIgqZmvIl/4UTXDGSdtv66Ly2SAhr9RJ0aQ3yxnK2huFsrWNZn2p8nSMjGfl5pcYWIq73W2iSnfG4ywSu0Fj98HpvzCuKHimjnqTSzskhmxkZGQ4LVUmct4KgvkJsUsUw1RvDm9CE8dVYxfAFNKUppQCFRuKkKicgGFROKkcVC8oBjihMcUID0sUoULdlK0oCQJyZlOCAUFKkS8kAyaVkUbpJXBkbRkucdgsZWcZSVstRHZG6oYTpM2ncu8u3yVV6QLtLVXhlBFr9SpJGibs9xPI98fkqrhemnkbWxyvbC0Pa8at/LIHwUV42bYUu5bLFhq6p+qWaNz9XtHGo/NU1Q6rku1doqRpYdAGAcDr9lpLdb4DVziSZzntePa8seazcVJTPkrZjPPqc52SR2I/VUxtHV1MVtJIltpqHW2CKepGmWp1ag5uTj8PwXl4gaWRRvmnc9/jHIz7hG/by+itrRQsay2skmdMwue/G47/AKqHiS1wCppczyhr3yMBxyy0H8k2u8OK/t+Smss0rBBHBpcyJzsnnqYHbBvz+Qwuh8PU0d0oWVlPhrXbOYdy0/j8QsA+01LoqmUOjlmpJ9JbH7J0YyA0k77dDzXRuAKinlsTW0srDJqLpY+Toz5t5hQ5VVyU7rWPwWIs0rjzZj8VU8UyfsamZrc3D3DxMcmN7n4rZMeSPaPLssPfanN0rKSelM8hGuIOb7Dm+ffCVjU+CMOTdeozVzlhuFeymDi1lGA5zhy1HfPw6dDtyVpbZKl1vicydjA95ds5uewHnsPoqCWirKaSogpIIjG9gf7fs+Dl24b/AHeo7Y2V9w9QSOslKJKwDGrIaD/aKs36C2JP9QbxG6rkslQDVNJjcx4OW5HtD48lViorI6qhmFW7m3OW5znI328itBd7c19nrmetyFngOOnfpuszNQ0XqdFK8yloI7dDn/WFMNOSuaL7+EawVNdTzfu543Fp95pB+YV/auIBJNHSXAiOaQHw5Cdnke78twqKeio/HY0iTOA4HVscjKpuJGzUjKNuPGY6YvDm827Y++FSXyaZ4/xKmjqvU5ymlUnCNyfXWwNmeXyxEt1uG725OCrvK1OBrT0NcdlC4qV5UDihA1yhkKe4qFxQEbjuhNcd0ID1tKkao2kKRqAkCcE0FKgH5UNbUso6SaplxohjdIcnGQBlSZWZ9Icz28NyUsbwJK2WOnac8w52/wBAUfglLbMjbHGppo21A1yVUUlVITsS5xyCorNIY+Ig15y2qic3fvs4ff6r0QExX1sYGGMh0N/AKsrJ4qaugqNej1WpaxwB6Ht83/ILCW22j18sRjiaRpLa8+LWSk7anDP4NWZhcG0cryeZ+h1Z/wBKsam5Pp7dXyQUwcwuk0k5BOXbfkqJ9ZIKWnibStBlOOZwNRx/6z81bHDMuo6mXRq7ewtko2n/AJdKD8SvPxk4x2+lnb/EyoJ+mCpYq6pbcpSyONnhtbHpyN8BeDiO4PfFSQy0mWve9x056f7qsy3RplzTOJLR6adhNzuRjd7ErdWPNjsA/T6rRWExivZJGxjJSwh+kYPx/rqsnZLhAamqinZJE+Fjxloz7zs/dXvDrqWnvMRjnklfKCwahyG5/NTSasiMirDSN7GdYyFn+J3MZNA8YbIM+11AV9TH9yXD5rKX5raq6AvkaPBI0tz88rS36Tk6NJ5Vv4M5cZHPulSXncUeN+ezXOVjw47Npawe5I8fUfqqmtnp473URzTHU+DGGtJ5tLfzU/Dd1hNFVCOB79NQdJPUEfyVHLcHTOaZy8GicBJFJGeT43NPyWKia59kLfejx9ef+QLVRXOTWB6m0A7DPnssfFcKmN1ZE2nhDWl22G8g9uPoSoxwx1GZKvBrvG1w2+TnqjB+ir6qV1Tf/Dj3bEBG3Pfmf674XnornUihoRJTseBHnDQNgSe3ZeOGV9P6vOHhzpJg5zgeYzv9QPkEU6bLVkVY5NraKoUdwpYdhE4eCQNsHG31C1jlzy5+LFBLKz2XwvDwScbtcD+q3tNUCqp4qhuNMjA75q2N8cnJ1kSr3I9yhepXFQPK0OQjcVC8qRxUD0BG8oSFCA9THKZrl4o3+a9DHID1NKdlQtcpMoB+VgPSVUNkulht+cfvJKg7/wBlukf5j8lvQVyfjaaOs9IkcZeWer07Yg4E7E5J+pKivBfGt0iClmfTcQMbMXSRSNxv0+KqrlPDX0tzfFIQ8zuMee+M/l9V67zFPQXNlW0iWNrTkg74LcKirI6d9mkqYpvD8R7X5A98au34t5jqqY9cs7OqdJqS8uNU42KExwOxNICCMbjVn+yilNTNdrfEISQMOI25YB7dyU+tlfHwxbAHaSwxbN2xsp7VUyHiAudK46IT7x25qVfpIyYX3JfRZ0fr75Z5hC46pDnBP6qpv8s5rqJjqd+fCeeQOM/4Ve26VwjJDjkuJ5rx3ieT9vUQ8R2PCaCDvzcVSK9R09TgpSlsrrVUxniG4NczS18Uhxp0++T3P2Whss7Bd6RoBLTIMHX/APKr7VKH3acuZG/90Sct55H81d28wMrqctp4muEgwQPNKr1GeHFXZRtKf2KRwPQn7rEX6KM3epcdOSRnOey2pcBSu7l33WMvdPBJeKkyOeDkZx+CvkfBh0kt29GTqHU8d/h57iMEBwG2odwT37KThmsYx9fC1gJAjcBpJPUHmfyUtxhpYLnA8Qh5MRdl+/IE8l67VVspb9UQtia0PY8YDex/kpdLtCxUsm/+ntZPPgOjp3jqNh+ioqgVrLtcGNgcGkkj8NJ/ktZ607bD3D8DhUl4mdFdG1DpHeHUM0gEknIxnKpjvk6epwVw2eKmkqmw0viwPI8MbjHX4FVpuMht1OympxEBJjJ5nePl8ytFQVQmt8AY+T92PDIPIlux2PmCso4VctDMIINLGz41adIO5545/wAPXIVsb22Z9VjcxPJpqiKWqZV+JKSXtkGC7u0rYej+t9asDY3P1Pgdp37EAj7rHWylE8DJJ595NXstGR2Vj6LX+FV1FOJi5s1IyQNIxuxxBP8A5hIa5MOol6nj4OhOUL9lM4bKCQq5ykTioHlSu5qF6AY5Ca4oQDI3FehjiUIQE7XFTNJQhASBcV4geTx9WO6iq058tJQhVo36f3llf2twDj3VkamCM8NOfjBGs4HLlH0QhZYvB6PXpbkv7uA3h2kx7ro8JlvJbeqnH/TuQhSvayMv5V+xfUJIiOO68d0OriCAno2P7j9UqFTH5Onqvgjsbz+1Kg/9v/pCtbdUvkucTSGgB4O34hCEv3GWLiK/nwbyYkMYByMgWM4iley8VBDucmkjywhC1ze05f6f+R/Rnb64tq6Yg4zA77FPicRxM3+9rB+qEKF7TSvyP7LuJ5LATz05VLfpHet25nQiT8kIWeP3HV1X419i2l3h26AN6h7j5nUVUVUjzaajU4uAkyAeQ2lQhXn5KZ16INHZ9qKkxy8HP0R6OyW8RUAb71LM0/hkH8ghCY/LMes9q+jqDuZUEiELY8kgcoXpEICJyEIQH//Z"
              }
            />
            {children}
          </div>
          <div className="min-h-screen bg-white flex-1 flex-grow-[0.2]"></div>
        </div>
      </body>
    </html>
  );
}
